### ISSUE TITLE
orientation not working

### ISSUE THREAD

**Issue by ErAshu** [rajesht1989/iImagePickerController#1]
please provide the orientation. It is not working in portrait mode. image output is rotated

**Comment by rajesht1989** [comment]
Can you share a screenshot of the issue? @ErAshu

**Comment by ErAshu** [comment]
I take this picture with landscape mode.
![baeef388-8d61-4bd0-b544-1c1d9f7d436e](https://cloud.githubusercontent.com/assets/4178384/15680513/a05ffe6a-2773-11e6-9a21-c5dc0225168a.jpg)

**Comment by ErAshu** [comment]
Please fix this

**Comment by rajesht1989** [comment]
I'll look for feasibility

**Comment by rajesht1989** [comment]
@ErAshu issue fixed
